### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by edotenseilove** [phantamanta44/tconmodmod#1]
Hallo this is a best mod for me I have been waiting for something like that. Is this mode going to be updated because there are so many things that would be fantastic to see. Is this mode going to be supporting traits (posibility of adding traits as a modifiers) or maybe mutiple embossments? Also i think it would be great if this mode supports setting max lvl of modifier (for example beeing able to obtain lvl 10 of luck/fortune modifier)

**Comment by phantamanta44** [comment]
pretty much all of these cannot be done because of the way TCon's code is structured. sorry

**Comment by phantamanta44** [comment]
ok so it turns out i'm wrong after some experimentation:

1. traits can already be used as modifiers; you can simply use a "material" mutation to give it a modifier material. the caveat is that the check for stackability is hard-coded, so trait-modifiers can only be applied at most once, and only if the tool didn't already have that trait.

2. it turns out, it's totally possible to modify the max level of a modifier with a little bit of hacky stuff. the caveats are that:
* it may not work for third-party (e.g. plustic or extratic) modifiers
* localization keys don't exist for high-level modifiers; any sharpness level above 5 will still display as "Sharpestest" unless you manually add localization keys for them

will get back to you on the embossment thing.

**Comment by phantamanta44** [comment]
![2019-08-03_12 59 06](https://user-images.githubusercontent.com/5924141/62415385-8a617f00-b5ee-11e9-9639-1ad1737d1511.png)
it works! expect a new release soon

**Comment by phantamanta44** [comment]
i think i can safely say that this is now closed. grab the new release [here](https://www.curseforge.com/minecraft/mc-mods/tinkers-modifier-modifier/files/2754106)
